from sklearn.neighbors import KNeighborsClassifier
from k_NN_training_final_project import knn_builder, run_knn
import joblib

import os
os.makedirs("models", exist_ok=True)

print("K-NN MODEL:")
# knn_model = knn_builder(1, 'uniform', 2)    # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(2, 'uniform', 2)    # Test accuracy: 0.52
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(3, 'uniform', 2)    # Test accuracy: 0.70
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(4, 'uniform', 2)    # Test accuracy: 0.64
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(5, 'uniform', 2)    # Test accuracy: 0.62
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(6, 'uniform', 2)    # Test accuracy: 0.64
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(7, 'uniform', 2)    # Test accuracy: 0.56
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(8, 'uniform', 2)    # Test accuracy: 0.58
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(9, 'uniform', 2)    # Test accuracy: 0.54
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(10, 'uniform', 2)   # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(15, 'uniform', 2)   # Test accuracy: 0.64
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(20, 'uniform', 2)   # Test accuracy: 0.64
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(25, 'uniform', 2)   # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(30, 'uniform', 2)   # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(32, 'uniform', 2)   # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(64, 'uniform', 2)   # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(128, 'uniform', 2)  # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(256, 'uniform', 2)  # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)

# knn_model = knn_builder(1, 'uniform', 1)    # Test accuracy: 0.58
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(2, 'uniform', 1)    # Test accuracy: 0.54
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(3, 'uniform', 1)    # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(4, 'uniform', 1)    # Test accuracy: 0.58
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(5, 'uniform', 1)    # Test accuracy: 0.58
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(6, 'uniform', 1)    # Test accuracy: 0.62
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(7, 'uniform', 1)    # Test accuracy: 0.58
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(8, 'uniform', 1)    # Test accuracy: 0.60
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(9, 'uniform', 1)    # Test accuracy: 0.56
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(10, 'uniform', 1)   # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(15, 'uniform', 1)   # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(20, 'uniform', 1)   # Test accuracy: 0.64
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(25, 'uniform', 1)   # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(30, 'uniform', 1)   # Test accuracy: 0.66
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(32, 'uniform', 1)   # Test accuracy: 0.70
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(64, 'uniform', 1)   # Test accuracy: 0.68
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(128, 'uniform', 1)  # Test accuracy: 0.70
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(256, 'uniform', 1)  # Test accuracy: 0.70
# knn_test_accuracy = run_knn(knn_model)


# knn_model = knn_builder(1, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(2, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(3, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(4, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(5, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(6, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(7, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(8, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(9, 'distance', 2)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(10, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(15, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(20, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(25, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(30, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(32, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(64, 'distance', 2)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(128, 'distance', 2)  # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(256, 'distance', 2)  # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)

# knn_model = knn_builder(1, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(2, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(3, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(4, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(5, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(6, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(7, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(8, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(9, 'distance', 1)    # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(10, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(15, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(20, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(25, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(30, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(32, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(64, 'distance', 1)   # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
# knn_model = knn_builder(128, 'distance', 1)  # Test accuracy: 0.
# knn_test_accuracy = run_knn(knn_model)
knn_model = knn_builder(256, 'distance', 1)  # Test accuracy: 0.
knn_test_accuracy = run_knn(knn_model)


joblib.dump(knn_model, "models/knn_model.pkl")
